version: '3.7'

services:
  backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile_base
    command: shell
    environment:
      - DEBUG=${DEBUG:-True}
      - APP_LOGGING_LEVEL=${APP_LOGGING_LEVEL:-INFO}
      - DB_LOGGING_LEVEL=${DB_LOGGING_LEVEL:-INFO}
      - DJANGO_SETTINGS_MODULE=backend_test.settings
      - APP=backend_test
      - QUEUES=celery
      - PYTHONDONTWRITEBYTECODE=1
      # forwarded from the host if they exist
      - UPDATE_PYTHON_REQUIREMENTS_ON_CONTAINERSTART
    volumes:
      - .:/opt/cornershop/backend-test
    ports:
      - 8000:8000
    depends_on:
      - jupyterlab
      - postgres
      - redis
  jupyterlab:
    build:
      context: .
      dockerfile: .docker/Dockerfile_base
    command: jupyterlab
    ports:
      - 8001:8000
    volumes:
      - .:/opt/cornershop/backend-test
    environment:
      - DJANGO_SETTINGS_MODULE=backend_test.settings
      - PYTHONDONTWRITEBYTECODE=1
      - DJANGO_ALLOW_ASYNC_UNSAFE=true
      - APP=backend_test
      - QUEUES=celery
      # forwarded from the host if they exist
      - UPDATE_PYTHON_REQUIREMENTS_ON_CONTAINERSTART
  postgres:
    image: circleci/postgres:12.3-postgis
    volumes:
      - postgres123-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
  testdb:
    image: circleci/postgres:12.3-postgis-ram
    environment:
      - POSTGRES_USER=testdb
      - POSTGRES_PASSWORD=testdb
      - POSTGRES_DB=testdb
    ports:
      - 5433:5432
  redis:
    image: redis:5.0.7-alpine
    volumes:
      - redis-data:/data
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:1337
    volumes:
      - .:/code
    ports: 
      - "1337:1337"  
    depends_on: 
      - postgres
    environment:
      - PYTHONUNBUFFERED=1
  celery:
    build: .
    command: celery worker --app=backend_test --loglevel=info 
    volumes:
      - ./code:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
  dashboard:
    build: .
    command:  flower -A backend_test --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5555:5555
    environment:
      - DEBUG=1
      - SECRET_KEY=dbaa1_i7%*3r9-=z-+_mz4r-!qeed@(-a_r(g@k8jo8y3r27%m
      - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - web
      - redis
      - celery

volumes:
  postgres123-data: {}
  redis-data: {}
  elasticsearch-data: {}
  dynamodb-data: {}
  neo4j-data: {}
