# Generated by Django 3.0.8 on 2021-05-20 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('fecha_menu', models.DateField()),
                ('option', models.IntegerField()),
                ('desc_menu', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=300)),
                ('nationality', models.CharField(max_length=100)),
                ('access', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Selected',
            fields=[
                ('id_menu_select', models.BigAutoField(primary_key=True, serialize=False)),
                ('option_selected', models.IntegerField()),
                ('customization', models.CharField(max_length=250)),
                ('fecha_menu_selec', models.DateField()),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.Menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.User')),
            ],
        ),
    ]
