# Generated by Django 3.0.8 on 2021-05-20 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='option',
        ),
        migrations.AlterField(
            model_name='menu',
            name='desc_menu',
            field=models.CharField(max_length=500),
        ),
    ]
